# Generated by Django 6.0.3 on 2026-03-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Ticket Category (e.g. Adult, Child)', max_length=50)),
                ('ticket_count', models.IntegerField(default=1, help_text='Number of tickets issued')),
                ('latitude', models.FloatField(help_text='GPS Latitude')),
                ('longitude', models.FloatField(help_text='GPS Longitude')),
                ('timestamp', models.DateTimeField(help_text='Time of ticket issuance')),
                ('route', models.CharField(help_text='Route identifier (e.g. 201A, 335E)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
